auto: true
server: true
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
permalink: /:year/:month/:title/
paginate: 10

name: David Ensinger
description: David Ensinger is a Front End Developer from Columbus, OH
url: http://www.davidensinger.com